# Generated by Django 2.2.9 on 2020-01-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articel',
            new_name='Artikel',
        ),
    ]
