# Generated by Django 2.2.9 on 2020-01-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Jurnal', 'jurnal'), ('Berita', 'berita'), ('Blog', 'blog')], default='Blog', max_length=100),
        ),
    ]
