# Generated by Django 2.2.9 on 2020-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='Email@kosong.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
