# Generated by Django 2.2.9 on 2020-01-14 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200114_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waktu_posting',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
